AWSTemplateFormatVersion: '2010-09-09'
Description: 'lambda: Serverless Agent for Buildkite, a @wolfeidau template'
Transform: AWS::Serverless-2016-10-31
Parameters:
    EnvironmentName:
      Type: String
      Default: "dev"
      Description: "The name of the environment used to tag and name resources"
    EnvironmentNumber:
      Type: String
      Default: "1"
      Description: "The number of the environment used to tag and name resources"

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  AgentFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies: 
        - 
          PolicyName: "BuildkiteSfnFunctionAccess"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - states:DescribeStateMachine
                - states:StartExecution
                - states:ListExecutions
                Resource:
                - !Sub '${StateMachineCodebuildJobMonitor}'
              - Effect: Allow
                Action: 
                - 'ssm:DescribeParameters'
                Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action: 
                - 'ssm:GetParameters'
                - 'ssm:GetParameter'
                - 'ssm:PutParameter'
                Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvironmentName}/*"
        - 
          PolicyName: "BuildkiteDynamodbAccess"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt AgentTable.Arn
                  - !Sub '${AgentTable.Arn}/*'

  AgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: agent
      Timeout: 60
      MemorySize: 128
      Runtime: go1.x
      CodeUri: ./handler.zip
      Role: !Sub ${AgentFunctionRole.Arn}
      Environment:   
        Variables:
          LAMBDA_HANDLER: "agent-poll"
          ENVIRONMENT_NAME:
            Ref: EnvironmentName
          ENVIRONMENT_NUMBER:
            Ref: EnvironmentNumber
          SFN_CODEBUILD_JOB_MONITOR_ARN: !Sub '${StateMachineCodebuildJobMonitor}'
          AGENT_TABLE_NAME:
            Ref: AgentTable          
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  SfnFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action: 
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Policies: 
        - 
          PolicyName: "BuildkiteSfnFunctionAccess"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: 
                - 'ssm:GetParameters'
                - 'ssm:GetParameter'
                - 'ssm:DescribeParameters'
                Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvironmentName}/*"
              - Effect: Allow
                Action: 
                - 'ssm:DescribeParameters'
                Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action: 
                - 'codebuild:*'
                Resource:
                - "*"
              - Effect: Allow
                Action:
                - logs:GetLogEvents
                Resource:
                - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
        - 
          PolicyName: "BuildkiteDynamodbAccess"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - !GetAtt AgentTable.Arn
                  - !Sub '${AgentTable.Arn}/*'

  SubmitJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: agent
      Timeout: 30
      Runtime: go1.x
      MemorySize: 128
      CodeUri: ./handler.zip
      Role: !Sub ${SfnFunctionRole.Arn}
      Environment:
        Variables:
          LAMBDA_HANDLER: "submit-job"
          ENVIRONMENT_NAME:
            Ref: EnvironmentName
          ENVIRONMENT_NUMBER:
            Ref: EnvironmentNumber
          AGENT_TABLE_NAME:
            Ref: AgentTable

  CheckJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: agent
      Timeout: 30
      Runtime: go1.x
      MemorySize: 128
      CodeUri: ./handler.zip
      Role: !Sub ${SfnFunctionRole.Arn}
      Environment:
        Variables:
          LAMBDA_HANDLER: "check-job"
          ENVIRONMENT_NAME:
            Ref: EnvironmentName
          ENVIRONMENT_NUMBER:
            Ref: EnvironmentNumber
          AGENT_TABLE_NAME:
            Ref: AgentTable

  CompleteJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: agent
      Timeout: 30
      Runtime: go1.x
      MemorySize: 128
      CodeUri: ./handler.zip
      Role: !Sub ${SfnFunctionRole.Arn}
      Environment:
        Variables:
          LAMBDA_HANDLER: "complete-job"
          ENVIRONMENT_NAME:
            Ref: EnvironmentName
          ENVIRONMENT_NUMBER:
            Ref: EnvironmentNumber
          AGENT_TABLE_NAME:
            Ref: AgentTable

  StateMachineCodebuildJobMonitor:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: !Sub "CodebuildJobMonitor-${EnvironmentName}-${EnvironmentNumber}"
      DefinitionString: 
        Fn::Sub:
          - |
            {
              "Comment": "A state machine that submits a codebuild Job and monitors the Job until it completes.",
              "StartAt": "Submit Job",
              "States": {
                "Submit Job": {
                  "Type": "Task",
                  "Resource": "${SfnSubmitLambdaARN}",
                  "Next": "Wait X Seconds",
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "States.ALL"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ],
                  "Catch": [ 
                    {
                      "ErrorEquals": [ "States.ALL" ],
                      "Next": "Get Final Job Status",
                      "ResultPath": "$.task_status"
                    }
                  ]
                },
                "Wait X Seconds": {
                  "Type": "Wait",
                  "SecondsPath": "$.wait_time",
                  "Next": "Get Job Status"
                },
                "Get Job Status": {
                  "Type": "Task",
                  "Resource": "${SfnCheckLambdaARN}",
                  "Next": "Job Complete?",
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "States.ALL"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ],
                  "Catch": [ 
                    {
                      "ErrorEquals": [ "States.ALL" ],
                      "Next": "Get Final Job Status",
                      "ResultPath": "$.task_status"
                    }
                  ]
                },
                "Job Complete?": {
                  "Type": "Choice",
                  "Choices": [
                    {
                      "Variable": "$.task_status",
                      "StringEquals": "STOPPED",
                      "Next": "Get Final Job Status"
                    },
                    {
                      "Variable": "$.task_status",
                      "StringEquals": "FAILED",
                      "Next": "Get Final Job Status"
                    },
                    {
                      "Variable": "$.task_status",
                      "StringEquals": "SUCCEEDED",
                      "Next": "Get Final Job Status"
                    }
                  ],
                  "Default": "Wait X Seconds"
                },
                "Get Final Job Status": {
                  "Type": "Task",
                  "Resource": "${SfnCompleteLambdaARN}",
                  "End": true,
                  "Retry": [
                    {
                      "ErrorEquals": [
                        "States.ALL"
                      ],
                      "IntervalSeconds": 1,
                      "MaxAttempts": 3,
                      "BackoffRate": 2
                    }
                  ]
                }
              }
            }
          - SfnSubmitLambdaARN: !GetAtt SubmitJobFunction.Arn
            SfnCheckLambdaARN: !GetAtt CheckJobFunction.Arn
            SfnCompleteLambdaARN: !GetAtt CompleteJobFunction.Arn
      RoleArn: !GetAtt 'RoleCodebuildJobMonitor.Arn'

  RoleCodebuildJobMonitor:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: !Sub 'states.${AWS::Region}.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 'lambda:InvokeFunction'
            Resource:
            - !GetAtt SubmitJobFunction.Arn
            - !GetAtt CheckJobFunction.Arn
            - !GetAtt CompleteJobFunction.Arn

  AgentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: name
          KeyType: RANGE          
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expires
        Enabled: true

  AgentFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "AgentFunctionErrors"
      AlarmDescription: "Alarm if lambda errors out too many times"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
      - Name: "FunctionName"
        Value: !Ref AgentFunction
      Statistic: "Sum"
      ComparisonOperator: "GreaterThanThreshold"
      Threshold: 0
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: "breaching"

  SubmitJobFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "SubmitJobFunctionErrors"
      AlarmDescription: "Alarm if lambda errors out too many times"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
      - Name: "FunctionName"
        Value: !Ref SubmitJobFunction
      Statistic: "Sum"
      ComparisonOperator: "GreaterThanThreshold"
      Threshold: 0
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: "notBreaching"

  CheckJobFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "CheckJobFunctionErrors"
      AlarmDescription: "Alarm if lambda errors out too many times"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
      - Name: "FunctionName"
        Value: !Ref CheckJobFunction
      Statistic: "Sum"
      ComparisonOperator: "GreaterThanThreshold"
      Threshold: 0
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: "notBreaching"

  CompleteJobFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "CompleteJobFunctionErrors"
      AlarmDescription: "Alarm if lambda errors out too many times"
      Namespace: "AWS/Lambda"
      MetricName: "Errors"
      Dimensions:
      - Name: "FunctionName"
        Value: !Ref CompleteJobFunction
      Statistic: "Sum"
      ComparisonOperator: "GreaterThanThreshold"
      Threshold: 0
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: "notBreaching"

Outputs:  
  EnvironmentName:
    Value: !Ref EnvironmentName
    Export:
      Name: !Sub "${AWS::StackName}-EnvironmentName"
  EnvironmentNumber:
    Value: !Ref EnvironmentNumber
    Export:
      Name: !Sub "${AWS::StackName}-EnvironmentNumber"
  AgentFunctionArn:
    Value: !GetAtt AgentFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AgentFunctionArn"
  SubmitJobFunctionArn:
    Value: !GetAtt SubmitJobFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SubmitJobFunctionArn"
  CheckJobFunctionArn:
    Value: !GetAtt CheckJobFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CheckJobFunctionArn"
  CompleteJobFunctionArn:
    Value: !GetAtt CompleteJobFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CompleteJobFunctionArn"
  StateMachineCodebuildJobMonitorArn:
    Value: !Ref StateMachineCodebuildJobMonitor
    Export:
      Name: !Sub "${AWS::StackName}-StateMachineCodebuildJobMonitorArn"
  ArtifactBucket:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub "${AWS::StackName}-ArtifactBucket"
  AgentFunctionAlarm:
    Value: !Ref AgentFunctionAlarm
    Export:
      Name: !Sub "${AWS::StackName}-AgentFunctionAlarm"
  SubmitJobFunctionAlarm:
    Value: !Ref SubmitJobFunctionAlarm
    Export:
      Name: !Sub "${AWS::StackName}-SubmitJobFunctionAlarm"
  CheckJobFunctionAlarm:
    Value: !Ref CheckJobFunctionAlarm
    Export:
      Name: !Sub "${AWS::StackName}-CheckJobFunctionAlarm"
  CompleteJobFunctionAlarm:
    Value: !Ref CompleteJobFunctionAlarm
    Export:
      Name: !Sub "${AWS::StackName}-CompleteJobFunctionAlarm"
