steps:
  - name: ":golang:"
    command: "make ci"
    env:
      CB_IMAGE_OVERRIDE: "wolfeidau/codebuild-buildkite-golang:1.11"
      CB_COMPUTE_TYPE_OVERRIDE: "BUILD_GENERAL1_SMALL"
      CB_PRIVILEGED_MODE_OVERRIDE: "true"
      GO111MODULE: "on"
    agents:
      queue: dev
      serverless: true