// Code generated by mockery v1.0.0
package mocks

import api "github.com/buildkite/agent/api"
import mock "github.com/stretchr/testify/mock"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// GetAgentConfig provides a mock function with given fields: _a0
func (_m *Store) GetAgentConfig(_a0 string) (*api.Agent, error) {
	ret := _m.Called(_a0)

	var r0 *api.Agent
	if rf, ok := ret.Get(0).(func(string) *api.Agent); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Agent)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAgentKey provides a mock function with given fields: _a0
func (_m *Store) GetAgentKey(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAgentConfig provides a mock function with given fields: _a0, _a1
func (_m *Store) SaveAgentConfig(_a0 string, _a1 *api.Agent) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *api.Agent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
