AWSTemplateFormatVersion: '2010-09-09'
Description: 'lambda: Deployer codebuild project which links to the Serverless Agent for Buildkite, a @wolfeidau template'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Name:
    Type: String
  EnvironmentName:
    Type: String
  EnvironmentNumber:
    Type: String
  BuildkiteAgentPeerStack: 
    Type: String
  SourceName:
    Type: String

Resources:

  BuildkiteProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub BuildkiteProject-${EnvironmentName}-${EnvironmentNumber}-${Name}
      Artifacts:
        Type: no_artifacts
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        # using my custom codebuild docker image with buildkite installed along with golang
        Image: wolfeidau/codebuild-docker-buildkite:17.09.0 
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables: 
        - Name: ENVIRONMENT_NAME
          Type: "PLAINTEXT"
          Value: !Sub "${EnvironmentName}"
        - Name: ENVIRONMENT_NUMBER
          Type: "PLAINTEXT"
          Value: !Sub "${EnvironmentNumber}"
        - Name: ARTIFACT_BUCKET_NAME
          Type: "PLAINTEXT"
          Value: 
            'Fn::ImportValue': !Sub "${BuildkiteAgentPeerStack}-ArtifactBucket"
      ServiceRole: !Ref BuildkiteCodeBuildRole
      Source:
        Type: S3
        Location: 
          'Fn::Sub': 
          - "arn:aws:s3:::${SourceBucket}/${SourceName}"
          - SourceBucket: 
              'Fn::ImportValue': !Sub "${BuildkiteAgentPeerStack}-SourceBucket"
            Name: !Sub "${Name}"

  BuildkiteCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: BuildkiteSSMAccess
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: 'ssm:DescribeParameters'
            Resource:
            - '*'
          - Effect: Allow
            Action: 
            - 'ssm:GetParameters'
            - 'ssm:GetParameter'
            Resource:
            - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvironmentName}/${EnvironmentNumber}/*"
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/BuildkiteProject-${EnvironmentName}-${EnvironmentNumber}-${Name}*"
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
            Resource:
            - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:GetObjectVersion
            Resource:
            - 'Fn::Sub': 
              - "arn:aws:s3:::${SourceBucket}/*"
              - SourceBucket: 
                  'Fn::ImportValue': !Sub "${BuildkiteAgentPeerStack}-SourceBucket"
          - Effect: Allow
            Action:
            - 's3:ListAllMyBuckets'
            Resource:
            - '*'
          - Effect: Allow
            Action:
            - s3:ListBucket
            - s3:PutObject
            - s3:GetObject
            - s3:GetObjectVersion
            Resource:
            - 'Fn::Sub': 
              - "arn:aws:s3:::${ArtifactBucket}/*"
              - ArtifactBucket: 
                  'Fn::ImportValue': !Sub "${BuildkiteAgentPeerStack}-ArtifactBucket"
            - 'Fn::Sub': 
              - "arn:aws:s3:::${ArtifactBucket}"
              - ArtifactBucket: 
                  'Fn::ImportValue': !Sub "${BuildkiteAgentPeerStack}-ArtifactBucket"
          # Need this to deploy all the things.
          # NOTE: You probably want to tune this depending on the isolation you have within your account!!
          - Effect: Allow
            Action:
            - '*'
            Resource:
            - '*'

Outputs:
  BuildkiteProject:
    Value: !Ref BuildkiteProject
    Export:
      Name: !Sub "${AWS::StackName}-BuildkiteProject"
